export const Countries = [
  { name: 'Afghanistan', code: 'AF', isChecked: false },
  { name: 'Åland Islands', code: 'AX', isChecked: false },
  { name: 'Albania', code: 'AL', isChecked: false },
  { name: 'Algeria', code: 'DZ', isChecked: false },
  { name: 'American Samoa', code: 'AS', isChecked: true },
  { name: 'AndorrA', code: 'AD', isChecked: false },
  { name: 'Angola', code: 'AO', isChecked: false },
  { name: 'Anguilla', code: 'AI', isChecked: false },
  { name: 'Antarctica', code: 'AQ', isChecked: false },
  { name: 'Antigua and Barbuda', code: 'AG', isChecked: false },
  { name: 'Argentina', code: 'AR', isChecked: false },
  { name: 'Armenia', code: 'AM', isChecked: false },
  { name: 'Aruba', code: 'AW', isChecked: false },
  { name: 'Australia', code: 'AU', isChecked: false },
  { name: 'Austria', code: 'AT', isChecked: false },
  { name: 'Azerbaijan', code: 'AZ', isChecked: false },
  { name: 'Bahamas', code: 'BS', isChecked: false },
  { name: 'Bahrain', code: 'BH', isChecked: false },
  { name: 'Bangladesh', code: 'BD', isChecked: false },
  { name: 'Barbados', code: 'BB', isChecked: false },
  { name: 'Belarus', code: 'BY', isChecked: false },
  { name: 'Belgium', code: 'BE', isChecked: false },
  { name: 'Belize', code: 'BZ', isChecked: false },
  { name: 'Benin', code: 'BJ', isChecked: false },
  { name: 'Bermuda', code: 'BM', isChecked: false },
  { name: 'Bhutan', code: 'BT', isChecked: false },
  { name: 'Bolivia', code: 'BO', isChecked: false },
  { name: 'Bosnia and Herzegovina', code: 'BA', isChecked: false },
  { name: 'Botswana', code: 'BW', isChecked: false },
  { name: 'Bouvet Island', code: 'BV', isChecked: false },
  { name: 'Brazil', code: 'BR', isChecked: false },
  { name: 'British Indian Ocean Territory', code: 'IO', isChecked: false },
  { name: 'Brunei Darussalam', code: 'BN', isChecked: false },
  { name: 'Bulgaria', code: 'BG', isChecked: false },
  { name: 'Burkina Faso', code: 'BF', isChecked: false },
  { name: 'Burundi', code: 'BI', isChecked: false },
  { name: 'Cambodia', code: 'KH', isChecked: false },
  { name: 'Cameroon', code: 'CM', isChecked: false },
  { name: 'Canada', code: 'CA', isChecked: false },
  { name: 'Cape Verde', code: 'CV', isChecked: false },
  { name: 'Cayman Islands', code: 'KY', isChecked: false },
  { name: 'Central African Republic', code: 'CF', isChecked: false },
  { name: 'Chad', code: 'TD', isChecked: false },
  { name: 'Chile', code: 'CL', isChecked: false },
  { name: 'China', code: 'CN', isChecked: false },
  { name: 'Christmas Island', code: 'CX', isChecked: false },
  { name: 'Cocos (Keeling) Islands', code: 'CC', isChecked: false },
  { name: 'Colombia', code: 'CO', isChecked: false },
  { name: 'Comoros', code: 'KM', isChecked: false },
  { name: 'Congo', code: 'CG', isChecked: false },
  {
    name: 'Congo, The Democratic Republic of the',
    code: 'CD',
    isChecked: false
  },
  { name: 'Cook Islands', code: 'CK', isChecked: false },
  { name: 'Costa Rica', code: 'CR', isChecked: false },
  { name: 'Cote D"Ivoire', code: 'CI', isChecked: false },
  { name: 'Croatia', code: 'HR', isChecked: false },
  { name: 'Cuba', code: 'CU', isChecked: false },
  { name: 'Cyprus', code: 'CY', isChecked: false },
  { name: 'Czech Republic', code: 'CZ', isChecked: false },
  { name: 'Denmark', code: 'DK', isChecked: false },
  { name: 'Djibouti', code: 'DJ', isChecked: false },
  { name: 'Dominica', code: 'DM', isChecked: false },
  { name: 'Dominican Republic', code: 'DO', isChecked: false },
  { name: 'Ecuador', code: 'EC', isChecked: false },
  { name: 'Egypt', code: 'EG', isChecked: false },
  { name: 'El Salvador', code: 'SV', isChecked: false },
  { name: 'Equatorial Guinea', code: 'GQ', isChecked: false },
  { name: 'Eritrea', code: 'ER', isChecked: false },
  { name: 'Estonia', code: 'EE', isChecked: false },
  { name: 'Ethiopia', code: 'ET', isChecked: false },
  { name: 'Falkland Islands (Malvinas)', code: 'FK', isChecked: false },
  { name: 'Faroe Islands', code: 'FO', isChecked: false },
  { name: 'Fiji', code: 'FJ', isChecked: false },
  { name: 'Finland', code: 'FI', isChecked: false },
  { name: 'France', code: 'FR', isChecked: false },
  { name: 'French Guiana', code: 'GF', isChecked: false },
  { name: 'French Polynesia', code: 'PF', isChecked: false },
  { name: 'French Southern Territories', code: 'TF', isChecked: false },
  { name: 'Gabon', code: 'GA', isChecked: false },
  { name: 'Gambia', code: 'GM', isChecked: false },
  { name: 'Georgia', code: 'GE', isChecked: false },
  { name: 'Germany', code: 'DE', isChecked: false },
  { name: 'Ghana', code: 'GH', isChecked: false },
  { name: 'Gibraltar', code: 'GI', isChecked: false },
  { name: 'Greece', code: 'GR', isChecked: false },
  { name: 'Greenland', code: 'GL', isChecked: false },
  { name: 'Grenada', code: 'GD', isChecked: false },
  { name: 'Guadeloupe', code: 'GP', isChecked: false },
  { name: 'Guam', code: 'GU', isChecked: false },
  { name: 'Guatemala', code: 'GT', isChecked: false },
  { name: 'Guernsey', code: 'GG', isChecked: false },
  { name: 'Guinea', code: 'GN', isChecked: false },
  { name: 'Guinea-Bissau', code: 'GW', isChecked: false },
  { name: 'Guyana', code: 'GY', isChecked: false },
  { name: 'Haiti', code: 'HT', isChecked: false },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM', isChecked: false },
  { name: 'Holy See (Vatican City State)', code: 'VA', isChecked: false },
  { name: 'Honduras', code: 'HN', isChecked: false },
  { name: 'Hong Kong', code: 'HK', isChecked: false },
  { name: 'Hungary', code: 'HU', isChecked: false },
  { name: 'Iceland', code: 'IS', isChecked: false },
  { name: 'India', code: 'IN', isChecked: false },
  { name: 'Indonesia', code: 'ID', isChecked: false },
  { name: 'Iran, Islamic Republic Of', code: 'IR', isChecked: false },
  { name: 'Iraq', code: 'IQ', isChecked: false },
  { name: 'Ireland', code: 'IE', isChecked: false },
  { name: 'Isle of Man', code: 'IM', isChecked: false },
  { name: 'Israel', code: 'IL', isChecked: false },
  { name: 'Italy', code: 'IT', isChecked: false },
  { name: 'Jamaica', code: 'JM', isChecked: false },
  { name: 'Japan', code: 'JP', isChecked: false },
  { name: 'Jersey', code: 'JE', isChecked: false },
  { name: 'Jordan', code: 'JO', isChecked: false },
  { name: 'Kazakhstan', code: 'KZ', isChecked: false },
  { name: 'Kenya', code: 'KE', isChecked: false },
  { name: 'Kiribati', code: 'KI', isChecked: false },
  {
    name: 'Korea, Democratic People"S Republic of',
    code: 'KP',
    isChecked: false
  },
  { name: 'Korea, Republic of', code: 'KR', isChecked: false },
  { name: 'Kuwait', code: 'KW', isChecked: false },
  { name: 'Kyrgyzstan', code: 'KG', isChecked: false },
  { name: 'Lao People"S Democratic Republic', code: 'LA', isChecked: false },
  { name: 'Latvia', code: 'LV', isChecked: false },
  { name: 'Lebanon', code: 'LB', isChecked: false },
  { name: 'Lesotho', code: 'LS', isChecked: false },
  { name: 'Liberia', code: 'LR', isChecked: false },
  { name: 'Libyan Arab Jamahiriya', code: 'LY', isChecked: false },
  { name: 'Liechtenstein', code: 'LI', isChecked: false },
  { name: 'Lithuania', code: 'LT', isChecked: false },
  { name: 'Luxembourg', code: 'LU', isChecked: false },
  { name: 'Macao', code: 'MO', isChecked: false },
  {
    name: 'Macedonia, The Former Yugoslav Republic of',
    code: 'MK',
    isChecked: false
  },
  { name: 'Madagascar', code: 'MG', isChecked: false },
  { name: 'Malawi', code: 'MW', isChecked: false },
  { name: 'Malaysia', code: 'MY', isChecked: false },
  { name: 'Maldives', code: 'MV', isChecked: false },
  { name: 'Mali', code: 'ML', isChecked: false },
  { name: 'Malta', code: 'MT', isChecked: false },
  { name: 'Marshall Islands', code: 'MH', isChecked: false },
  { name: 'Martinique', code: 'MQ', isChecked: false },
  { name: 'Mauritania', code: 'MR', isChecked: false },
  { name: 'Mauritius', code: 'MU', isChecked: false },
  { name: 'Mayotte', code: 'YT', isChecked: false },
  { name: 'Mexico', code: 'MX', isChecked: false },
  { name: 'Micronesia, Federated States of', code: 'FM', isChecked: false },
  { name: 'Moldova, Republic of', code: 'MD', isChecked: false },
  { name: 'Monaco', code: 'MC', isChecked: false },
  { name: 'Mongolia', code: 'MN', isChecked: false },
  { name: 'Montserrat', code: 'MS', isChecked: false },
  { name: 'Morocco', code: 'MA', isChecked: false },
  { name: 'Mozambique', code: 'MZ', isChecked: false },
  { name: 'Myanmar', code: 'MM', isChecked: false },
  { name: 'Namibia', code: 'NA', isChecked: false },
  { name: 'Nauru', code: 'NR', isChecked: false },
  { name: 'Nepal', code: 'NP', isChecked: false },
  { name: 'Netherlands', code: 'NL', isChecked: false },
  { name: 'Netherlands Antilles', code: 'AN', isChecked: false },
  { name: 'New Caledonia', code: 'NC', isChecked: false },
  { name: 'New Zealand', code: 'NZ', isChecked: false },
  { name: 'Nicaragua', code: 'NI', isChecked: false },
  { name: 'Niger', code: 'NE', isChecked: false },
  { name: 'Nigeria', code: 'NG', isChecked: false },
  { name: 'Niue', code: 'NU', isChecked: false },
  { name: 'Norfolk Island', code: 'NF', isChecked: false },
  { name: 'Northern Mariana Islands', code: 'MP', isChecked: false },
  { name: 'Norway', code: 'NO', isChecked: false },
  { name: 'Oman', code: 'OM', isChecked: false },
  { name: 'Pakistan', code: 'PK', isChecked: false },
  { name: 'Palau', code: 'PW', isChecked: false },
  { name: 'Palestinian Territory, Occupied', code: 'PS', isChecked: false },
  { name: 'Panama', code: 'PA', isChecked: false },
  { name: 'Papua New Guinea', code: 'PG', isChecked: false },
  { name: 'Paraguay', code: 'PY', isChecked: false },
  { name: 'Peru', code: 'PE', isChecked: false },
  { name: 'Philippines', code: 'PH', isChecked: false },
  { name: 'Pitcairn', code: 'PN', isChecked: false },
  { name: 'Poland', code: 'PL', isChecked: false },
  { name: 'Portugal', code: 'PT', isChecked: false },
  { name: 'Puerto Rico', code: 'PR', isChecked: false },
  { name: 'Qatar', code: 'QA', isChecked: false },
  { name: 'Reunion', code: 'RE', isChecked: false },
  { name: 'Romania', code: 'RO', isChecked: false },
  { name: 'Russian Federation', code: 'RU', isChecked: false },
  { name: 'RWANDA', code: 'RW', isChecked: false },
  { name: 'Saint Helena', code: 'SH', isChecked: false },
  { name: 'Saint Kitts and Nevis', code: 'KN', isChecked: false },
  { name: 'Saint Lucia', code: 'LC', isChecked: false },
  { name: 'Saint Pierre and Miquelon', code: 'PM', isChecked: false },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', isChecked: false },
  { name: 'Samoa', code: 'WS', isChecked: false },
  { name: 'San Marino', code: 'SM', isChecked: false },
  { name: 'Sao Tome and Principe', code: 'ST', isChecked: false },
  { name: 'Saudi Arabia', code: 'SA', isChecked: false },
  { name: 'Senegal', code: 'SN', isChecked: false },
  { name: 'Serbia and Montenegro', code: 'CS', isChecked: false },
  { name: 'Seychelles', code: 'SC', isChecked: false },
  { name: 'Sierra Leone', code: 'SL', isChecked: false },
  { name: 'Singapore', code: 'SG', isChecked: false },
  { name: 'Slovakia', code: 'SK', isChecked: false },
  { name: 'Slovenia', code: 'SI', isChecked: false },
  { name: 'Solomon Islands', code: 'SB', isChecked: false },
  { name: 'Somalia', code: 'SO', isChecked: false },
  { name: 'South Africa', code: 'ZA', isChecked: false },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    isChecked: false
  },
  { name: 'Spain', code: 'ES', isChecked: false },
  { name: 'Sri Lanka', code: 'LK', isChecked: false },
  { name: 'Sudan', code: 'SD', isChecked: false },
  { name: 'Suriname', code: 'SR', isChecked: false },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', isChecked: false },
  { name: 'Swaziland', code: 'SZ', isChecked: false },
  { name: 'Sweden', code: 'SE', isChecked: false },
  { name: 'Switzerland', code: 'CH', isChecked: false },
  { name: 'Syrian Arab Republic', code: 'SY', isChecked: false },
  { name: 'Taiwan, Province of China', code: 'TW', isChecked: false },
  { name: 'Tajikistan', code: 'TJ', isChecked: false },
  { name: 'Tanzania, United Republic of', code: 'TZ', isChecked: false },
  { name: 'Thailand', code: 'TH', isChecked: false },
  { name: 'Timor-Leste', code: 'TL', isChecked: false },
  { name: 'Togo', code: 'TG', isChecked: false },
  { name: 'Tokelau', code: 'TK', isChecked: false },
  { name: 'Tonga', code: 'TO', isChecked: false },
  { name: 'Trinidad and Tobago', code: 'TT', isChecked: false },
  { name: 'Tunisia', code: 'TN', isChecked: false },
  { name: 'Turkey', code: 'TR', isChecked: false },
  { name: 'Turkmenistan', code: 'TM', isChecked: false },
  { name: 'Turks and Caicos Islands', code: 'TC', isChecked: false },
  { name: 'Tuvalu', code: 'TV', isChecked: false },
  { name: 'Uganda', code: 'UG', isChecked: false },
  { name: 'Ukraine', code: 'UA', isChecked: false },
  { name: 'United Arab Emirates', code: 'AE', isChecked: false },
  { name: 'United Kingdom', code: 'GB', isChecked: false },
  { name: 'United States', code: 'US', isChecked: false },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UM',
    isChecked: false
  },
  { name: 'Uruguay', code: 'UY', isChecked: false },
  { name: 'Uzbekistan', code: 'UZ', isChecked: false },
  { name: 'Vanuatu', code: 'VU', isChecked: false },
  { name: 'Venezuela', code: 'VE', isChecked: false },
  { name: 'Viet Nam', code: 'VN', isChecked: false },
  { name: 'Virgin Islands, British', code: 'VG', isChecked: false },
  { name: 'Virgin Islands, U.S.', code: 'VI', isChecked: false },
  { name: 'Wallis and Futuna', code: 'WF', isChecked: false },
  { name: 'Western Sahara', code: 'EH', isChecked: false },
  { name: 'Yemen', code: 'YE', isChecked: false },
  { name: 'Zambia', code: 'ZM', isChecked: false },
  { name: 'Zimbabwe', code: 'ZW' }
];

export type CountriesTypes = typeof Countries[0];
